# generated by datamodel-codegen:
#   filename:  review.json
#   timestamp: 2026-07-18T21:53:09+00:00

from __future__ import annotations

from msgspec import Struct


class Review(Struct):
    review_id: str
    user_id: str
    business_id: str
    stars: float
    useful: int
    funny: int
    cool: int
    text: str
    date: str
