# generated by datamodel-codegen:
#   filename:  user.json
#   timestamp: 2026-07-18T21:53:10+00:00

from __future__ import annotations

from msgspec import Struct


class User(Struct):
    user_id: str
    name: str
    review_count: int
    yelping_since: str
    useful: int
    funny: int
    cool: int
    elite: str
    friends: str
    fans: int
    average_stars: float
    compliment_hot: int
    compliment_more: int
    compliment_profile: int
    compliment_cute: int
    compliment_list: int
    compliment_note: int
    compliment_plain: int
    compliment_cool: int
    compliment_funny: int
    compliment_writer: int
    compliment_photos: int
