# generated by datamodel-codegen:
#   filename:  business.json
#   timestamp: 2026-07-18T21:53:09+00:00

from __future__ import annotations

from msgspec import UNSET, Struct, UnsetType


class Attributes(Struct):
    ByAppointmentOnly: str | UnsetType = UNSET
    BusinessAcceptsCreditCards: str | UnsetType = UNSET
    BikeParking: str | UnsetType = UNSET
    RestaurantsPriceRange2: str | UnsetType = UNSET
    CoatCheck: str | UnsetType = UNSET
    RestaurantsTakeOut: str | UnsetType = UNSET
    RestaurantsDelivery: str | UnsetType = UNSET
    Caters: str | UnsetType = UNSET
    WiFi: str | UnsetType = UNSET
    BusinessParking: str | UnsetType = UNSET
    WheelchairAccessible: str | UnsetType = UNSET
    HappyHour: str | UnsetType = UNSET
    OutdoorSeating: str | UnsetType = UNSET
    HasTV: str | UnsetType = UNSET
    RestaurantsReservations: str | UnsetType = UNSET
    DogsAllowed: str | UnsetType = UNSET
    Alcohol: str | UnsetType = UNSET
    GoodForKids: str | UnsetType = UNSET
    RestaurantsAttire: str | UnsetType = UNSET
    Ambience: str | UnsetType = UNSET
    RestaurantsTableService: str | UnsetType = UNSET
    RestaurantsGoodForGroups: str | UnsetType = UNSET
    DriveThru: str | UnsetType = UNSET
    NoiseLevel: str | UnsetType = UNSET
    GoodForMeal: str | UnsetType = UNSET
    BusinessAcceptsBitcoin: str | UnsetType = UNSET
    Smoking: str | UnsetType = UNSET
    Music: str | UnsetType = UNSET
    GoodForDancing: str | UnsetType = UNSET
    AcceptsInsurance: str | UnsetType = UNSET
    BestNights: str | UnsetType = UNSET
    BYOB: str | UnsetType = UNSET
    Corkage: str | UnsetType = UNSET
    BYOBCorkage: str | UnsetType = UNSET
    HairSpecializesIn: str | UnsetType = UNSET
    Open24Hours: str | UnsetType = UNSET
    RestaurantsCounterService: str | UnsetType = UNSET
    AgesAllowed: str | UnsetType = UNSET
    DietaryRestrictions: str | UnsetType = UNSET


class Hours(Struct):
    Monday: str | UnsetType = UNSET
    Tuesday: str | UnsetType = UNSET
    Wednesday: str | UnsetType = UNSET
    Thursday: str | UnsetType = UNSET
    Friday: str | UnsetType = UNSET
    Saturday: str | UnsetType = UNSET
    Sunday: str | UnsetType = UNSET


class Business(Struct):
    business_id: str
    name: str
    address: str
    city: str
    state: str
    postal_code: str
    latitude: float
    longitude: float
    stars: float
    review_count: int
    is_open: int
    attributes: Attributes | None
    categories: str | None
    hours: Hours | None
