# generated by datamodel-codegen:
#   filename:  checkin.json
#   timestamp: 2026-07-21T17:20:47+00:00

from __future__ import annotations

from msgspec import Struct


class Checkin(Struct):
    business_id: str
    date: str
