# generated by datamodel-codegen:
#   filename:  tip.json
#   timestamp: 2026-07-18T21:53:09+00:00

from __future__ import annotations

from msgspec import Struct


class Tip(Struct):
    user_id: str
    business_id: str
    text: str
    date: str
    compliment_count: int
